// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUzp_9ylq1ao5bbLbMtpRf20CEcTzDUSQ',
    appId: '1:49291810820:web:f473b06a33fd7b920e3d51',
    messagingSenderId: '49291810820',
    projectId: 'grocery---flutter-course-704ed',
    authDomain: 'grocery---flutter-course-704ed.firebaseapp.com',
    storageBucket: 'grocery---flutter-course-704ed.appspot.com',
    measurementId: 'G-M63DFX1C5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ipfeMPEZPKHzxNAcb9Jlup7BWFuHFjQ',
    appId: '1:49291810820:android:7ca69b1b9f3ecb520e3d51',
    messagingSenderId: '49291810820',
    projectId: 'grocery---flutter-course-704ed',
    storageBucket: 'grocery---flutter-course-704ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBuVQOmroql_URWapQUHFDRr3MgCyQrMA',
    appId: '1:49291810820:ios:b9d99e23080b6b2e0e3d51',
    messagingSenderId: '49291810820',
    projectId: 'grocery---flutter-course-704ed',
    storageBucket: 'grocery---flutter-course-704ed.appspot.com',
    androidClientId: '49291810820-rp0h48tbnrj0cl50pibnqdc29t2hpcel.apps.googleusercontent.com',
    iosClientId: '49291810820-h7suvt6k2p30itatpp610ebargtn3mg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAppWebAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBuVQOmroql_URWapQUHFDRr3MgCyQrMA',
    appId: '1:49291810820:ios:b9d99e23080b6b2e0e3d51',
    messagingSenderId: '49291810820',
    projectId: 'grocery---flutter-course-704ed',
    storageBucket: 'grocery---flutter-course-704ed.appspot.com',
    androidClientId: '49291810820-rp0h48tbnrj0cl50pibnqdc29t2hpcel.apps.googleusercontent.com',
    iosClientId: '49291810820-h7suvt6k2p30itatpp610ebargtn3mg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAppWebAdminPanel',
  );
}
